export const SET_USERS = `SET_USERS`
export const SET_RESTAURANTS = `SET_RESTAURANTS`
export const SET_SELECTED_RESTAURANT = `SET_SELECTED_RESTAURANT`
export const SET_FAVORITES = `SET_FAVORITES`
export const SET_LOADING = `SET_LOADING`
export const SET_ERROR = `SET_ERROR`
export const SET_TOKEN = `SET_TOKEN`
export const SET_REGISTER_SUCCESS = `SET_REGISTER_SUCCESS`